name: out_of_order_cpu_coe197
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  
  fonts:
    - family: Nunito
      fonts:
        - asset: lib/layout/_fontstyles/Nunito-Regular.ttf
    - family: Roboto-Mono
      fonts:
        - asset: lib/layout/_fontstyles/RobotoMono-Regular.ttf
